import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
	return (
		<Html lang='en'>
			<Head />
			<meta httpEquiv='Content-Type' content='text/html; charset=utf-8' />
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
			<link
				href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;900&display=swap'
				rel='stylesheet'
			></link>
			<title>Pokemon</title>

			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
